services:
   mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: always
    networks:
      - localnet
    ports:
      - 1883:1883
      - 1884:1884
    volumes:
      - ./.data/mosquitto/config:/mosquitto/config
      - ./.data/mosquitto/data:/mosquitto/data
      - ./.data/mosquitto/log:/mosquitto/log

networks:
  localnet:
    driver: bridge