version: '3.9'
services:
    software:
        build: ./software
        ports:
        - "5000:5000"
        volumes:
        - ./software:/app
        - ./.data/software:/data
        environment:
        - FLASK_ENV=development