M48
; DRILL file {KiCad 8.0.2} date 2025-08-03T00:44:14+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-08-03T00:44:14+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1181
%
G90
G05
T1
X4.9551Y-5.8128
X5.1827Y-5.8128
T2
X7.7264Y-3.8307
X7.7264Y-5.126
T3
X5.3209Y-4.2126
X5.3209Y-4.7441
X7.435Y-4.2126
X7.435Y-4.7441
M30
